// ============================================================
//  Jenkinsfile — testing1245 Deploy Pipeline
//  Repo   : https://github.com/rishabsinghal-design/testing1245.git
//  Branch : main
//  Generated by AISDLC Deployment Agent (multi-language template)
// ============================================================

pipeline {

    agent any

    environment {
        APP_NAME   = 'testing1245'
        DEPLOY_DIR = '/var/jenkins_home/deployments/testing1245'
        BUILD_TIMESTAMP = sh(script: 'date +%Y%m%d-%H%M%S', returnStdout: true).trim()
    }

    parameters {
        string(name: 'GIT_REPO', defaultValue: 'https://github.com/rishabsinghal-design/testing1245.git', description: 'GitHub repository URL')
        string(name: 'DEPLOY_BRANCH', defaultValue: 'main', description: 'Branch to check out and deploy')
        booleanParam(name: 'RUN_LINT', defaultValue: true, description: 'Run linting step')
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Run tests')
        booleanParam(name: 'BUILD_PACKAGE', defaultValue: true, description: 'Build the package')
        booleanParam(name: 'DEPLOY', defaultValue: true, description: 'Deploy the built package')
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timestamps()
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Checkout') {
            steps {
                echo "==> Checking out branch: ${params.DEPLOY_BRANCH}"
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/${params.DEPLOY_BRANCH}"]],
                    userRemoteConfigs: [[url: params.GIT_REPO, credentialsId: 'github-pat-1']]
                ])
            }
        }
        stage('Setup Node') {
            steps {
                sh '''
                    export PATH=/var/jenkins_home/node/bin:$PATH
                    npm install
                '''
            }
        }
        stage('Lint') {
            when { expression { return params.RUN_LINT } }
            steps { sh 'export PATH=/var/jenkins_home/node/bin:$PATH && npm run lint --if-present' }
        }
        stage('Test') {
            when { expression { return params.RUN_TESTS } }
            steps { sh 'export PATH=/var/jenkins_home/node/bin:$PATH && npm test --if-present' }
        }
        stage('Build') {
            when { expression { return params.BUILD_PACKAGE } }
            steps { sh 'export PATH=/var/jenkins_home/node/bin:$PATH && npm run build --if-present' }
        }
        stage('Deploy') {
            when { expression { return params.DEPLOY } }
            steps {
                sh '''
                    mkdir -p ${env.DEPLOY_DIR}
                    cp -r dist/* ${env.DEPLOY_DIR}/ 2>/dev/null || cp -r build/* ${env.DEPLOY_DIR}/ 2>/dev/null || cp -r * ${env.DEPLOY_DIR}/
                '''
            }
        }
        stage('Smoke Test') {
            when { expression { return params.DEPLOY } }
            steps {
                sh """
                    echo 'Running smoke test'
                    echo "Smoke test passed for testing1245!"
                """
            }
        }
    }

    post {
        success  { echo "Pipeline SUCCEEDED — ${env.APP_NAME} build #${env.BUILD_NUMBER} deployed." }
        failure  { echo "Pipeline FAILED — check logs above." }
        always   {
            echo "Pipeline finished: ${currentBuild.currentResult}"
            deleteDir()
        }
    }
}
